A1Store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('/', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path, include
from . import views

app_name = "main_app"

urlpatterns = [
    path('products/', views.home, name='home'),
    path('products/<int:prod_id>', views.product_details, name='detail'),
    path('products/<int:prod_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('product/create/', views.product_create, name='product_create'),
    path('checkout/', views.cart_checkout, name='cart_checkout'),
    path('products/<int:pk>/update/', views.ProductUpdate.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDelete.as_view(), name='product_delete'),




    # path('about/', views.about, name='about'),
    # path('cats/', views.cats_index, name='index'),
    # # path('cats/', views.CatList.as_view(), name='index'),
    # path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    # path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    # path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    # path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    # path('cats/<int:cat_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    # path('cats/create/', views.CatCreate.as_view(), name='cats_create'),

    # New url pattern below
    #path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
CATEGORY = (
    ('F','Furniture'),
    ('T','Toy'),
    ('C','Cloth'),
    ('M','Mobile Phone'),
    ('L','Laptop'),
)



class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=600)
    price = models.DecimalField(max_digits=19, decimal_places=4)
    category =  models.CharField(
            max_length=1,
            # add the 'choices' field option
            choices=CATEGORY,
            # set the default value for meal to be 'B'
            default=CATEGORY[0][0]
        )
    
    class Meta:
        ordering = ['-price']

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f' product name : {self.name}, Category :{self.get_category_display()}, Price : {self.price}'
    
    def get_absolute_url(self):
        return reverse('main_app:detail', kwargs={'prod_id': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
         
        return f"Photo for cat_id: {self.product_id} @{self.url}"

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity =  models.IntegerField(default=1)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f'{self.id}'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ManyToManyField(Cart)

    def __str__(self):
        return str(self.product_id);

main_app/forms.py
from django.forms import ModelForm
from .models import Product

class ProductForm(ModelForm):
  class Meta:
    model = Product
    fields = ['name', 'description','price', 'category']

main_app/views.py
from django.shortcuts import render, redirect
from .models import Product, Photo, Order, Cart
from django.shortcuts import redirect, render
from django.http import HttpResponse
import boto3
from django.views import generic
import uuid
import traceback
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Import the mixin for class-based views
from django.contrib.auth.mixins import LoginRequiredMixin

S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'sb-a1store'


def find_logged_user_details(request):
  return {
    'id' : request.user.id,
    'username' : request.user.username,
    'is_superuser' : request.user.is_superuser,
  }


def home(request):
  logged_in_user = request.user
  products = Product.objects.all()
  return render(request, 'product/home.html',
  { 
    'products' : products, 
    'total_items_in_cart' : calculate_total_items_in_cart(request)
  })


@login_required(login_url='/accounts/login/')     
def product_create(request):
  if request.method == 'POST':
    product = Product.objects.create(
      name=request.POST.get('product_name'),
      description=request.POST.get('product_description'),
      price=request.POST.get('product_price'),
      category=request.POST.get('product_category')
      )
    product.save()
    print(product.id)
    # photo-file was the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
      s3 = boto3.client('s3')
      # need a unique "key" for S3 / needs image file extension too
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      # just in case something goes wrong
      try:
        s3.upload_fileobj(photo_file, BUCKET, key)
        # build the full url string
        url = f"{S3_BASE_URL}{BUCKET}/{key}"
        # we can assign to cat_id or cat (if you have a cat object)
        photo = Photo(url=url, product_id=product.id)
        photo.save()
      except:
        print('An error occurred uploading file to S3')
    return redirect('main_app:home')
  else:
    return render(request,'product/create.html')


def product_details(request, prod_id):
  logged_in_user_id = find_logged_user_details(request).get('id')
  total = Cart.objects.filter(user_id = logged_in_user_id).count()
  product = Product.objects.get(id=prod_id)
  return render(request, 'product/detail.html', 
  { 
    'product' : product, 
    'product_id' : prod_id,
    'total_items_in_cart' : calculate_total_items_in_cart(request)
  })

@login_required(login_url='/accounts/login/')     
def add_to_cart(request, prod_id):
  logged_in_user_id = find_logged_user_details(request).get('id')
  product = Product.objects.get(id=prod_id)
  item_exist_in_cart = Cart.objects.filter( product_id = product.id, user_id = logged_in_user_id )
  if item_exist_in_cart:
    existing_quantity = item_exist_in_cart[0].quantity   
    new_quantity = existing_quantity + 1 
    Cart.objects.filter( product_id = product.id, user_id = logged_in_user_id).update(quantity = new_quantity)
  else:
    cart = Cart.objects.create(product_id = product.id, user_id = logged_in_user_id)
    cart.save()
  
  return render(request, 'product/detail.html', 
  {
    'product' : product,
    'product_id' : prod_id,
    'total_items_in_cart' : calculate_total_items_in_cart(request)
  })


class ProductUpdate(LoginRequiredMixin, UpdateView):
  model = Product
  fields = ['name', 'description', 'price', 'category']


class ProductDelete(LoginRequiredMixin, DeleteView):
  model = Product
  success_url = '/products/'


def calculate_total_items_in_cart(request):
  logged_in_user = request.user
  products_in_cart = Cart.objects.filter(user_id = logged_in_user.id)
  print(products_in_cart)
  total_quantity = 0
  for product in products_in_cart:
      total_quantity += product.quantity
  return total_quantity

@login_required(login_url='/accounts/login/')     
def cart(request):
  logged_in_user_id = find_logged_user_details(request).get('id')
  tuples_of_all_items_in_cart = Cart.objects.filter(user_id = logged_in_user_id).values_list('product_id', 'quantity')
  items_in_cart, quantity = zip(*tuples_of_all_items_in_cart)
  products_in_cart = Product.objects.filter(id__in = items_in_cart) 
  modified_products_list = []

  index_of_modified_products_list = 0
  subtotal = 0
  def convert_model_to_list(product):
    return {
      'id': product.pk,
      'name': product.name,
      'description': product.description,
      'price': product.price,
      'category': product.category,
      'quantity': None
    }

  for product in list(products_in_cart):
    for pair_of_prod_id_and_quantity in tuples_of_all_items_in_cart:
      print(tuples_of_all_items_in_cart)
      if product.pk == pair_of_prod_id_and_quantity[0]:
        modified_products_list.append(convert_model_to_list(product))
        modified_products_list[index_of_modified_products_list]['quantity'] = pair_of_prod_id_and_quantity[1]
        subtotal += float(modified_products_list[index_of_modified_products_list]['price'] * modified_products_list[index_of_modified_products_list]['quantity'])
        index_of_modified_products_list += 1 
   
  tax =  13 / 100 * subtotal
  prod_total = subtotal + tax
  return render(request, 'cart.html', 
  {
    'products': modified_products_list,
    'product_photo_reference': products_in_cart,
    'subtotal' : subtotal,
    'tax' : tax,
    'prod_total' : prod_total,
    'total_items_in_cart' : calculate_total_items_in_cart(request)
  })



@login_required(login_url='/accounts/login/')     
def cart_checkout(request):
  logged_in_user_id = find_logged_user_details(request).get('id')
  checked_out_products = Cart.objects.filter(user_id = logged_in_user_id)
  print("checkout")
  checked_out_products.delete()
  # total = Cart.objects.filter(user_id = logged_in_user_id).count()
  print(f'Deleted products are : \n {checked_out_products}')
  return redirect('main_app:home')


def signup(request):
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      logged_in_user_id = find_logged_user_details(request).get('id')
      # created_new_cart_of_user = Cart.objects.create(user_id = logged_in_user_id)
      return redirect('main_app:home')  
      # or
      # return redirect('product/home.html')
  else:
    form = UserCreationForm()
  return render(request, 'registration/signup.html', 
  {
    'form': form
  })

main_app/templates/product/create.html
{% extends 'base.html' %}
{% block content%}
 <div>
    <h2>Please add new product</h2>

  <div class="card">
    <form action="{% url 'main_app:product_create' %}" enctype="multipart/form-data" method="post" class="card-panel">
      {% csrf_token %}
        <label for="product_name">Product name: </label>
        <input id="product_name" type="text" name="product_name">

        <label for="product_description">Product description: </label>
        <input id="product_description" type="text" name="product_description">

        <label for="product_price">Product price: </label>
        <input id="product_price" type="text" name="product_price">

        <label for="product_category">Product category: </label>
        <select name="product_category" id="product_category" class="form-control">
            <option value="None">--Select Category--</option>  
            <option value="F">Furniture</option>
            <option value="T">Toy</option>
            <option value="C">Cloth</option>
            <option value="M">Mobile Phone</option>
            <option value="L">Laptop</option>
        </select>
        <br><br>
        <input type="file" name="photo-file">
        <br><br>
        <input type="submit" class="btn" value="Add Product">
    </form>
  </div>
 </div>
<script>
  // add additional JS to initialize select below
  var selectEl = document.getElementById('product_category');
  M.FormSelect.init(selectEl);

</script>
{% endblock %}

main_app/templates/product/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Product Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <div class="card-content">
            <!-- Insert photo markup below this comment -->
              {% for photo in product.photo_set.all %}
                <img class="responsive-img card-panel" src="{{photo.url}}">
              {% empty %}
                <div class="card-panel teal-text center-align">No Photos Uploaded</div>
              {% endfor %}
        </div>
        <span class="card-title">{{ product.name }}</span>
        <p>Price: {{ product.price | floatformat:2 }}</p>
        <p>Description: {{ product.description }}</p>
      </div>
     
      <div class="card-action">
        <a href="{% url 'main_app:add_to_cart' prod_id=product_id %}" id="add_to_cart_btn">Add to cart</a>
        <a href="{% url 'main_app:home' %}">Back to Home</a>
        <br><br>
        {% if user.is_superuser%}
          <a href="{% url 'main_app:product_update' product_id %}">Edit</a>
          <a href="{% url 'main_app:product_delete' product_id %}">Delete</a>
        {% endif %}
        </div>
    </div>
    
  </div>
  
</div>


<script>
  // add additional JS to initialize select below
  var selectEl = document.getElementById('add_to_cart_btn');
  let products_in_cart = []
  products_in_cart.push(product)
  console.log(products_in_cart)
  //M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/product/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Product List</h1>
<div class="divider"></div>
{% for product in products %}
<div class="col s3">
  <div class="card">
    <div class="card-content">
      <!-- Insert photo markup below this comment -->
        {% for photo in product.photo_set.all %}
          <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
    </div>
    <a href=" {% url 'main_app:detail' product.id %}">
    <div class="card-content">
      <span class="card-title">{{ product.name }}</span>
      <p>Price: {{ product.price| floatformat:2 }}</p>
      <!-- <p>Description: {{ product.description }}</p> -->
    </div>
    </a>
  </div>
</div>
{% endfor %}
{% endblock %}

main_app/templates/product/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Product List</h1>
{% for product in products %}
<div class="col s3">
  <div class="card">
    <a href="dh[fdsfjks]">
    <div class="card-content">
      <span class="card-title">{{ product.name }}</span>
      <p>Price: {{ product.price| floatformat:2 }}</p>
      <!-- <p>Description: {{ product.description }}</p> -->
    </div>
    </a>
  </div>
</div>
{% endfor %}
{% endblock %}